### ISSUE TITLE
Clean up/restructure complicated queries

### ISSUE THREAD

**Issue by ferencmarkizay** [kszk-securiteam/wargame-web#1]

**Comment by szaszm** [comment]
We have some compilcated queries but I think they can be read if one has some familiarity with django's ORM. So I suggest only changing them when they need to be updated.

Any improvement suggestions are welcome though.

**Comment by ferencmarkizay** [comment]
I cleaned up the code in 10bf44058cae21646c732cc5d548ee7023af374a.
