### ISSUE TITLE
Internal admin page

### ISSUE THREAD

**Issue by ferencmarkizay** [kszk-securiteam/wargame-web#2]
- [x] Challenges (create, edit, delete, view private details)
- [ ] Submissions (delete, mark as correct), reset submissions for challenge
- [x] Users (password reset, hide)
- [ ] Config editor
- [ ] Import (users, challenges)

**Comment by szaszm** [comment]
Maybe we could adapt django's default admin view to support some of our desired features.

**Comment by szaszm** [comment]
update for record: `@ferencmarkizay` created a separate admin view for our custom functionality because changing the django admin view would mean much more unnecessary effort if it's even possible.

**Comment by ferencmarkizay** [comment]
This is mostly done, I created separate issues for the remaining tasks.
